- name: Add the apt-key for Docker
  apt_key: keyserver=hkp://p80.pool.sks-keyservers.net:80
           id=58118E89F3A912897C070ADBF76221572C52609D

- name: Add the Docker apt repo
  apt_repository: repo='deb https://apt.dockerproject.org/repo ubuntu-{{ubuntu_version}} main' state=present update_cache=yes

- name: Install Docker
  apt: pkg=docker-engine=1.9.1-0~{{ubuntu_version}} state=present force=yes
